on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - '.vscode'
      - 'README.md'
      - 'biome.json'
      - 'e2e'
      - '**/*/__tests__'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Build and Publish to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      # Build
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build

      # Publish
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: 'ecd17b79b9df5aa2ee0742371302caf3'
          projectName: 'vexpense'
          directory: 'dist'
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'